import type { QimenResult } from '@/lib/contracts/qimen';

type ReferenceBoard = {
  key: 'sh' | 'sz' | 'cyb';
  tabLabel: string;
  title: string;
  description: string;
  image: string;
  datetimeLabel: string;
  qimen: QimenResult;
};

export const referenceBoards = [
  {
    key: 'sh',
    tabLabel: '沪市',
    title: '沪市参考盘',
    description: '上证指数镇盘，用于比照沪市主盘气势。',
    image: '/ref-sh.svg',
    datetimeLabel: '上证指数 1990.12.19 09:30',
    qimen: {
      yinYang: '阴',
      ju: 7,
      valueStar: '禽芮',
      valueDoor: '死门',
      palaces: [
        {
          index: 0,
          position: 4,
          name: '巽',
          star: '天蓬',
          door: '开门',
          god: '玄武',
          skyGan: '己',
          skyExtraGan: null,
          groundGan: '壬',
          groundExtraGan: null,
          outGan: '庚',
          outExtraGan: null,
          branches: ['辰', '巳'],
          wuxing: '木',
          emptyMarkers: [],
        },
        {
          index: 1,
          position: 9,
          name: '离',
          star: '天任',
          door: '休门',
          god: '白虎',
          skyGan: '庚',
          skyExtraGan: null,
          groundGan: '乙',
          groundExtraGan: null,
          outGan: '丙',
          outExtraGan: null,
          branches: ['午'],
          wuxing: '火',
          emptyMarkers: [],
        },
        {
          index: 2,
          position: 2,
          name: '坤',
          star: '天冲',
          door: '生门',
          god: '六合',
          skyGan: '丙',
          skyExtraGan: null,
          groundGan: '丁',
          groundExtraGan: '辛',
          outGan: '戊',
          outExtraGan: null,
          branches: ['未', '申'],
          wuxing: '土',
          emptyMarkers: [],
        },
        {
          index: 3,
          position: 3,
          name: '震',
          star: '天心',
          door: '惊门',
          god: '九地',
          skyGan: '丁',
          skyExtraGan: '辛',
          groundGan: '癸',
          groundExtraGan: null,
          outGan: '己',
          outExtraGan: null,
          branches: ['卯'],
          wuxing: '木',
          emptyMarkers: [],
        },
        {
          index: 4,
          position: 5,
          name: '中',
          star: '天禽',
          door: '--',
          god: '--',
          skyGan: '',
          skyExtraGan: null,
          groundGan: '',
          groundExtraGan: null,
          outGan: null,
          outExtraGan: null,
          branches: [],
          wuxing: '土',
          emptyMarkers: [],
        },
        {
          index: 5,
          position: 7,
          name: '兑',
          star: '天辅',
          door: '伤门',
          god: '太阴',
          skyGan: '戊',
          skyExtraGan: null,
          groundGan: '己',
          groundExtraGan: null,
          outGan: '癸',
          outExtraGan: null,
          branches: ['酉'],
          wuxing: '金',
          emptyMarkers: [],
        },
        {
          index: 6,
          position: 8,
          name: '艮',
          star: '天柱',
          door: '死门',
          god: '九天',
          skyGan: '乙',
          skyExtraGan: null,
          groundGan: '戊',
          groundExtraGan: null,
          outGan: '丁',
          outExtraGan: '辛',
          branches: ['丑', '寅'],
          wuxing: '土',
          emptyMarkers: ['日空', '时空'],
        },
        {
          index: 7,
          position: 1,
          name: '坎',
          star: '天芮',
          door: '景门',
          god: '值符',
          skyGan: '壬',
          skyExtraGan: null,
          groundGan: '丙',
          groundExtraGan: null,
          outGan: '乙',
          outExtraGan: null,
          branches: ['子'],
          wuxing: '水',
          emptyMarkers: ['日空', '时空'],
        },
        {
          index: 8,
          position: 6,
          name: '乾',
          star: '天英',
          door: '杜门',
          god: '腾蛇',
          skyGan: '癸',
          skyExtraGan: null,
          groundGan: '庚',
          groundExtraGan: null,
          outGan: '壬',
          outExtraGan: null,
          branches: ['戌', '亥'],
          wuxing: '金',
          emptyMarkers: [],
        },
      ],
    },
  },
  {
    key: 'sz',
    tabLabel: '深市',
    title: '深市参考盘',
    description: '深证指数镇盘，用于比照深市主盘节奏。',
    image: '/ref-sz.svg',
    datetimeLabel: '深证指数 1994.07.20 09:30',
    qimen: {
      yinYang: '阴',
      ju: 5,
      valueStar: '天蓬',
      valueDoor: '休门',
      palaces: [
        {
          index: 0,
          position: 4,
          name: '巽',
          star: '天英',
          door: '开门',
          god: '白虎',
          skyGan: '乙',
          skyExtraGan: '癸',
          groundGan: '丁',
          groundExtraGan: null,
          outGan: '戊',
          outExtraGan: null,
          branches: ['辰', '巳'],
          wuxing: '木',
          emptyMarkers: [],
        },
        {
          index: 1,
          position: 9,
          name: '离',
          star: '天芮',
          door: '休门',
          god: '六合',
          skyGan: '辛',
          skyExtraGan: null,
          groundGan: '己',
          groundExtraGan: null,
          outGan: '壬',
          outExtraGan: null,
          branches: ['午'],
          wuxing: '火',
          emptyMarkers: [],
        },
        {
          index: 2,
          position: 2,
          name: '坤',
          star: '天柱',
          door: '生门',
          god: '太阴',
          skyGan: '壬',
          skyExtraGan: null,
          groundGan: '乙',
          groundExtraGan: '癸',
          outGan: '庚',
          outExtraGan: '乙',
          branches: ['未', '申'],
          wuxing: '土',
          emptyMarkers: [],
        },
        {
          index: 3,
          position: 3,
          name: '震',
          star: '天辅',
          door: '惊门',
          god: '玄武',
          skyGan: '己',
          skyExtraGan: null,
          groundGan: '丙',
          groundExtraGan: null,
          outGan: '己',
          outExtraGan: null,
          branches: ['卯'],
          wuxing: '木',
          emptyMarkers: ['日空', '时空'],
        },
        {
          index: 4,
          position: 5,
          name: '中',
          star: '天禽',
          door: '--',
          god: '--',
          skyGan: '',
          skyExtraGan: null,
          groundGan: '',
          groundExtraGan: null,
          outGan: null,
          outExtraGan: null,
          branches: [],
          wuxing: '土',
          emptyMarkers: [],
        },
        {
          index: 5,
          position: 7,
          name: '兑',
          star: '天心',
          door: '伤门',
          god: '腾蛇',
          skyGan: '戊',
          skyExtraGan: null,
          groundGan: '辛',
          groundExtraGan: null,
          outGan: '丁',
          outExtraGan: null,
          branches: ['酉'],
          wuxing: '金',
          emptyMarkers: [],
        },
        {
          index: 6,
          position: 8,
          name: '艮',
          star: '天冲',
          door: '死门',
          god: '九地',
          skyGan: '丁',
          skyExtraGan: null,
          groundGan: '庚',
          groundExtraGan: null,
          outGan: '癸',
          outExtraGan: null,
          branches: ['丑', '寅'],
          wuxing: '土',
          emptyMarkers: ['日空', '时空'],
        },
        {
          index: 7,
          position: 1,
          name: '坎',
          star: '天任',
          door: '景门',
          god: '九天',
          skyGan: '丙',
          skyExtraGan: null,
          groundGan: '戊',
          groundExtraGan: null,
          outGan: '辛',
          outExtraGan: null,
          branches: ['子'],
          wuxing: '水',
          emptyMarkers: [],
        },
        {
          index: 8,
          position: 6,
          name: '乾',
          star: '天蓬',
          door: '杜门',
          god: '值符',
          skyGan: '庚',
          skyExtraGan: null,
          groundGan: '壬',
          groundExtraGan: null,
          outGan: '丙',
          outExtraGan: null,
          branches: ['戌', '亥'],
          wuxing: '金',
          emptyMarkers: [],
        },
      ],
    },
  },
  {
    key: 'cyb',
    tabLabel: '创业板',
    title: '创业板参考盘',
    description: '创业板指镇盘，用于比照成长盘面势能。',
    image: '/ref-cyb.svg',
    datetimeLabel: '创业板指 2010.05.31 09:30',
    qimen: {
      yinYang: '阳',
      ju: 5,
      valueStar: '天柱',
      valueDoor: '惊门',
      palaces: [
        {
          index: 0,
          position: 4,
          name: '巽',
          star: '天任',
          door: '杜门',
          god: '六合',
          skyGan: '辛',
          skyExtraGan: null,
          groundGan: '乙',
          groundExtraGan: null,
          outGan: '丁',
          outExtraGan: '戊',
          branches: ['辰', '巳'],
          wuxing: '木',
          emptyMarkers: [],
        },
        {
          index: 1,
          position: 9,
          name: '离',
          star: '天冲',
          door: '景门',
          god: '白虎',
          skyGan: '丙',
          skyExtraGan: null,
          groundGan: '壬',
          groundExtraGan: null,
          outGan: '庚',
          outExtraGan: null,
          branches: ['午'],
          wuxing: '火',
          emptyMarkers: ['时空'],
        },
        {
          index: 2,
          position: 2,
          name: '坤',
          star: '天辅',
          door: '死门',
          god: '玄武',
          skyGan: '乙',
          skyExtraGan: null,
          groundGan: '丁',
          groundExtraGan: '戊',
          outGan: '己',
          outExtraGan: null,
          branches: ['未', '申'],
          wuxing: '土',
          emptyMarkers: ['日空', '时空'],
        },
        {
          index: 3,
          position: 3,
          name: '震',
          star: '天蓬',
          door: '伤门',
          god: '太阴',
          skyGan: '癸',
          skyExtraGan: null,
          groundGan: '丙',
          groundExtraGan: null,
          outGan: '壬',
          outExtraGan: null,
          branches: ['卯'],
          wuxing: '木',
          emptyMarkers: [],
        },
        {
          index: 4,
          position: 5,
          name: '中',
          star: '天禽',
          door: '--',
          god: '--',
          skyGan: '',
          skyExtraGan: null,
          groundGan: '',
          groundExtraGan: null,
          outGan: null,
          outExtraGan: null,
          branches: [],
          wuxing: '土',
          emptyMarkers: [],
        },
        {
          index: 5,
          position: 7,
          name: '兑',
          star: '天英',
          door: '惊门',
          god: '九地',
          skyGan: '壬',
          skyExtraGan: null,
          groundGan: '庚',
          groundExtraGan: null,
          outGan: '癸',
          outExtraGan: null,
          branches: ['酉'],
          wuxing: '金',
          emptyMarkers: ['日空'],
        },
        {
          index: 6,
          position: 8,
          name: '艮',
          star: '天心',
          door: '生门',
          god: '腾蛇',
          skyGan: '己',
          skyExtraGan: null,
          groundGan: '辛',
          groundExtraGan: null,
          outGan: '乙',
          outExtraGan: null,
          branches: ['丑', '寅'],
          wuxing: '土',
          emptyMarkers: [],
        },
        {
          index: 7,
          position: 1,
          name: '坎',
          star: '天柱',
          door: '休门',
          god: '值符',
          skyGan: '庚',
          skyExtraGan: null,
          groundGan: '癸',
          groundExtraGan: null,
          outGan: '丙',
          outExtraGan: null,
          branches: ['子'],
          wuxing: '水',
          emptyMarkers: [],
        },
        {
          index: 8,
          position: 6,
          name: '乾',
          star: '天芮',
          door: '开门',
          god: '九天',
          skyGan: '丁',
          skyExtraGan: '戊',
          groundGan: '己',
          groundExtraGan: null,
          outGan: '辛',
          outExtraGan: null,
          branches: ['戌', '亥'],
          wuxing: '金',
          emptyMarkers: [],
        },
      ],
    },
  },
] as const satisfies readonly ReferenceBoard[];
